apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: caikit-tgis-serving
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: caikit-tgis-serving
    app.kubernetes.io/part-of: kserve
  name: caikit-tgis-serving
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: caikit-tgis-serving
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: caikit-tgis-serving
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/caikit-tgis-serving@sha256:02865c0a4929f41a5a8a623e3955d3e548adf620d4eab5e8513f8db7fa33412c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
