apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-qpext
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/dchouras/kserve-qpext@sha256:7c8c8bebf2489c9a31bacad34f73d821991df26bbc88da9a4e62fd1ade14de4d
        name: container-image
        resources: {}
status: {}
