apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-28
    app.kubernetes.io/part-of: kserve
  name: kserve-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-28
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-28@sha256:89cace5fa08003552650930d084cbdc6b021490240a593e1b9531f1577540050
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
