apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-28@sha256:1942ea53d9c9be2fb5226c8e877fcafa00e3a0f0e495d3f9e9e1173c9c6e9a53
        name: container-image
        resources: {}
status: {}
