apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-qpext-rhoai-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-qpext-rhoai-rhtap
    app.kubernetes.io/part-of: kserve
  name: kserve-qpext-rhoai-rhtaphgww
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kserve-qpext-rhoai-rhtap
    weight: 100
status: {}
