apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-alibi-explainer
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-alibi-explainer@sha256:440e9633ffc298e95c1881aeac7f9853e4bb542e8804401f855df417c31c770f
        name: container-image
        resources: {}
status: {}
