apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: caikit-tgis-serving
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/caikit-tgis-serving@sha256:02865c0a4929f41a5a8a623e3955d3e548adf620d4eab5e8513f8db7fa33412c
        name: container-image
        resources: {}
status: {}
