apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-agent-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-agent-rhtap
    app.kubernetes.io/part-of: kserve
  name: kserve-agent-rhtap
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-agent-rhtap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-agent-rhtap
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-agent-rhtap@sha256:ac9f8aa9ee85e49cd227613b9dfe70f57157d62fcc3154177e467ac919de48f2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
