apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-agent-rhtap
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-agent-rhtap@sha256:ac9f8aa9ee85e49cd227613b9dfe70f57157d62fcc3154177e467ac919de48f2
        name: container-image
        resources: {}
status: {}
