apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-agent-rhtap
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-agent-rhtap@sha256:c88473cf09127aa644c1ae7971073de0290ffcc1bde2fe7bc45a23511d641987
        name: container-image
        resources: {}
status: {}
