apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-agent-rhtap
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-agent-rhtap@sha256:c56b2872844cc2349e5ac64dd12755a620385ded5a3037e14a63396670ee26e5
        name: container-image
        resources: {}
status: {}
