apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: kserve
  name: kserve
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve@sha256:b7ceba36073b982a7f63a6b77f13269991e7f634c5a376aa1d89a9e4bb50e2d5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
