apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-controller
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-controller@sha256:644cd6308dad22a3434339e72a81d0dd0aae59c199c0b70e61970f0386813df2
        name: container-image
        resources: {}
status: {}
