apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-qpext-rhoai-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-qpext-rhoai-rhtap
    app.kubernetes.io/part-of: kserve
  name: kserve-qpext-rhoai-rhtap
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-qpext-rhoai-rhtap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-qpext-rhoai-rhtap
    spec:
      containers:
      - image: quay.io/dchouras/kserve-qpext@sha256:d3c092486c84ced0ca2adc18545adb8d4b9086d3056d3ee6d3a46e53c994022a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
