apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-agent-rhoai-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-agent-rhoai-rhtap
    app.kubernetes.io/part-of: kserve
  name: kserve-agent-rhoai-rhtap
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-agent-rhoai-rhtap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-agent-rhoai-rhtap
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve/kserve-agent-rhoai-rhtap@sha256:37921c6f8d6d5924f9279de97e81f03cd0525233d533de484190569b61a7a6c8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
