apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-qpext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-qpext
    app.kubernetes.io/part-of: kserve
  name: kserve-qpext
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-qpext
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-qpext
    spec:
      containers:
      - image: quay.io/dchouras/kserve-qpext@sha256:7c8c8bebf2489c9a31bacad34f73d821991df26bbc88da9a4e62fd1ade14de4d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
